// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC2i6_jchUJR8jSGguajqsImhC1zMjJJU',
    appId: '1:431803598996:web:7972e9dd32dd35bb6ccc81',
    messagingSenderId: '431803598996',
    projectId: 'firstproject-b60b4',
    authDomain: 'firstproject-b60b4.firebaseapp.com',
    storageBucket: 'firstproject-b60b4.firebasestorage.app',
    measurementId: 'G-T4F51TB7KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvlFH3R9xRmjBo_nHY2bgJ1mzehz_GmkU',
    appId: '1:431803598996:android:9b227bcd5f4863096ccc81',
    messagingSenderId: '431803598996',
    projectId: 'firstproject-b60b4',
    storageBucket: 'firstproject-b60b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxDTahggfRro1RuL9C_NZnI9r_OfLYIqs',
    appId: '1:431803598996:ios:69c10113a72baaa66ccc81',
    messagingSenderId: '431803598996',
    projectId: 'firstproject-b60b4',
    storageBucket: 'firstproject-b60b4.firebasestorage.app',
    iosClientId: '431803598996-dqllgtse2k4r1r8go2nq1te2hei6584l.apps.googleusercontent.com',
    iosBundleId: 'com.skgezhil.clubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxDTahggfRro1RuL9C_NZnI9r_OfLYIqs',
    appId: '1:431803598996:ios:69c10113a72baaa66ccc81',
    messagingSenderId: '431803598996',
    projectId: 'firstproject-b60b4',
    storageBucket: 'firstproject-b60b4.firebasestorage.app',
    iosClientId: '431803598996-dqllgtse2k4r1r8go2nq1te2hei6584l.apps.googleusercontent.com',
    iosBundleId: 'com.skgezhil.clubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3HKeRYjwFM7oWXYBnvjErPQhEIP2D_UQ',
    appId: '1:431803598996:web:a5a7c028917a5e836ccc81',
    messagingSenderId: '431803598996',
    projectId: 'firstproject-b60b4',
    authDomain: 'firstproject-b60b4.firebaseapp.com',
    storageBucket: 'firstproject-b60b4.firebasestorage.app',
    measurementId: 'G-8JQ56C7RQX',
  );
}
